### ISSUE TITLE
Move live examples from earthdata to github.io

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/gibs-web-examples#10]
Currently our web examples live on the earthdata website itself:
https://earthdata.nasa.gov/labs/gibs/examples/openlayers/geographic-epsg4326.html

We should move them to github.io for easier management, e.g.:
https://nasa-gibs.github.io/gibs-web-examples/

**Comment by ZachTRice** [comment]
- [ ] [Create a nasa-gibs.github.io GitHub repo](https://pages.github.com/) - Make as private repo to protect API keys.
- [ ] [Create doc folder in master & change setting to serve from doc folder](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch) 
- [ ] Move each (compiled if applicable) example project into it's own folder in the nasa-gibs.github.io docs folder.

**Comment by ZachTRice** [comment]
This has now been setup to use the master branch of this repository. References on the homepage have been changed to point to the github.io pages.
