### ISSUE TITLE
Add a Mapbox GL JS example

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/gibs-web-examples#15]
https://www.mapbox.com/mapbox-gl-js/api/
https://github.com/mapbox/mapbox-gl-js

**Comment by cyrilchapon** [comment]
Any update on this ?
:)

**Comment by ZachTRice** [comment]
NASA is currently closed due to a lapse in Government funding.  We will respond to your requests once the Government is back to normal operations and we have had an opportunity to evaluate your request.  Thank you.

**Comment by ZachTRice** [comment]
Hey @cyrilchapon we have this on our radar but do not currently have an ETA on this. If you have any interest in developing a working example we would be very happy to review it and provide it as an example.

**Comment by mike-mcgann** [comment]
Available here:

https://github.com/nasa-gibs/gibs-web-examples/blob/master/examples/mapbox-gl/webmercator-epsg3857.js
