### ISSUE TITLE
What method is used to publish wmts with time?

### ISSUE THREAD

**Issue by bianbian886** [nasa-gibs/gibs-web-examples#26]
is GIBS includes three core software projects: The Imagery Exchange (TIE), OnEarth, and the Meta Raster Format (MRF) project？ more detail ，thx

**Comment by rboller** [comment]
Hello, GIBS primarily consists of OnEarth and the Meta Raster Format (MRF) project along with scripts to manage imagery ingest.  The Imagery Exchange (TIE) is no longer actively used.

**Comment by ZachTRice** [comment]
Closing this issue. Please feel free to reach out again if you have additional questions.
