### ISSUE TITLE
OSM_Land_mask Example

### ISSUE THREAD

**Issue by grwhumphries** [nasa-gibs/gibs-web-examples#3]
An example of how to use either the OSM_Land_mask or ocean/land mask would be good to add here as well.  

Using the same setup as exampled here for MODIS, the Land_mask does not work. 

var graysource = new ol.source.WMTS({
    url: "//map1.vis.earthdata.nasa.gov/wmts-antarctic/wmts.cgi?SERVICE=WMTS",
    layer: "OSM_Land_Mask",
    extent: [-4194304, -4194304, 4194304, 4194304],
    format: "image/png",
    matrixSet: "EPSG3031_250m",

```
tileGrid: new ol.tilegrid.WMTS({
    origin: [-4194304, 4194304],
    resolutions: [
        8192.0,
        4096.0,
        2048.0,
        1024.0,
        512.0,
        256.0
    ],
    matrixIds: [0, 1, 2, 3, 4, 5],
    tileSize: 512
})
```

});

**Comment by grwhumphries** [comment]
On the web-page:  https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+Available+Imagery+Products#expand-ReferenceLayers

Layer is listed as "OSM_Land_Mask" 
But XML file shows that this is actually "SCAR_Land_Mask"

Needs to be fixed either in XML or on the web page. Thanks!

**Comment by rboller** [comment]
Ah, thanks for pointing that out.  The land mask was a special case where the layer name was different for the Antarctic projection.  I've updated the wiki page to reflect this, please let us know if you notice any other problems!
