### ISSUE TITLE
CORS issues running locally

### ISSUE THREAD

**Issue by scottnc27603** [nasa-gibs/gibs-web-examples#30]
I'm trying to run the examples(cesium) locally and I'm running into CORS problems which isn't too surprising.  Is there anyway to get around this problem?

**Comment by mike-mcgann** [comment]
Are you directly opening the HTML files in the web browser? If so, install the mini web-server with `npm install` and `npm start` and that should work.

**Comment by scottnc27603** [comment]
I'm not exactly what I did last night, but I got the samples running
today.  Some tiles were missing here and there, but at least I got some
imagery layers.  Thanks for the email.  I want to load imagery from AVHRR
Satellite data, and Modis Satellite Data.  I don'r guess you know anything
about that...  haha

**Comment by mike-mcgann** [comment]
Glad you got it working.
