### ISSUE TITLE
Update OpenLayers 3 example

### ISSUE THREAD

**Issue by claudep** [nasa-gibs/gibs-web-examples#4]
`ol.layer.WMTS` is no more in recent OpenLayers 3 releases. It would be nice to update the examples. (I know, instability of OL3 API sucks!).

**Comment by rboller** [comment]
Thanks for mentioning this - I just upgraded the examples to OpenLayers 3.15.1 and it seemed to work without complaining.  We've been using ol.source.WMTS so I'm not sure that we were affected by the API change you describe.  Should I be looking somewhere else?

**Comment by claudep** [comment]
Sorry, I don't know what I've done, but I was able to make it work without errors, too. Thanks for looking at it!

**Comment by rboller** [comment]
No problem, it was a good excuse to upgrade the examples!
